#.github/workflows/build-package.yml
name: Build and Package Universal Widget

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target platform (e.g., Zendesk, Salesforce, ServiceNow)'
        required: true
        default: 'Zendesk'
    
      config: # New input for configuration array
        description: 'Configuration settings (e.g., ["setting1", "setting2"])'
        required: false
        type: string # Representing an array as a JSON string
        default: '' # Default to an empty JSON array string

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout universal-widget-v2 repository
        uses: actions/checkout@v4
        with:
          path: universal-widget-v2

      - name: Checkout widget-templates repository
        uses: actions/checkout@v4
        with:
          repository: soumyabera-aisera/widget-templates
          path: widget-templates

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies for universal-widget-v2
        run: npm install
        working-directory: universal-widget-v2

      - name: Build Universal Widget for Zendesk
        if: github.event.inputs.platform == 'Zendesk'
        run: npm run build:zendesk
        working-directory: universal-widget-v2 # Run build command from within the widget repo

      - name: Assemble Zendesk App Package
        if: github.event.inputs.platform == 'Zendesk'
        run: |
          echo "Assembling Zendesk package..."
          # Create the main package directory
          mkdir -p zendesk-app-package
          # Create the assets/build subdirectory
          mkdir -p zendesk-app-package/assets/build

          # Copy the index.html shell from widget-templates to zendesk-app-package/assets/build/
          cp widget-templates/zendesk-template/index.html zendesk-app-package/assets/build/

          # Copy the generated JS and CSS bundles from universal-widget-v2/dist-zendesk/assets/build/
          # These will have hashed filenames, e.g., main.[hash].js, main.[hash].css
          cp universal-widget-v2/dist-zendesk/assets/build/* zendesk-app-package/assets/build/ || true

          # Copy manifest.json and zcli.apps.config.json to the root of the package
          cp widget-templates/zendesk-template/manifest.json zendesk-app-package/
          cp widget-templates/zendesk-template/zcli.apps.config.json zendesk-app-package/
          # Copy translations to the translations/ directory
          mkdir -p zendesk-app-package/translations
          cp widget-templates/zendesk-template/translations/en.json zendesk-app-package/translations/
          # Copy other static assets (logos, screenshots etc.) directly into the assets/ folder
          cp widget-templates/zendesk-template/assets/* zendesk-app-package/assets/ || true

          echo "Zendesk package content:"
          ls -R zendesk-app-package/
        working-directory: .

      - name: Install ZCLI
        if: github.event.inputs.platform == 'Zendesk'
        run: npm install @zendesk/zcli -g # Install ZCLI globally

      - name: Validate, Package, and Deploy to Zendesk
        if: github.event.inputs.platform == 'Zendesk'
        env:
          ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
        run: |
          echo "Deploying Zendesk app using zcli..."
          zcli apps:package ./zendesk-app-package
          # zcli apps:update takes the app directory and handles packaging internally
          zcli apps:update ./zendesk-app-package
        working-directory: . # Run from the root of the runner

      - name: Upload Zendesk App Artifact
        if: github.event.inputs.platform == 'Zendesk'
        uses: actions/upload-artifact@v4
        with:
          name: zendesk-app-package
          # zcli apps:update creates the package in a 'tmp' directory at the execution root before uploading
          path: zendesk-app-package/tmp/app.zip
          retention-days: 5

      - name: Handle Salesforce (Not Implemented Yet)
        if: github.event.inputs.platform == 'Salesforce'
        run: echo "Salesforce packaging is not yet implemented. Please refer to the documentation for manual steps."

      - name: Handle ServiceNow (Not Implemented Yet)
        if: github.event.inputs.platform == 'ServiceNow'
        run: echo "ServiceNow packaging is not yet implemented. Please refer to the documentation for manual steps."