#.github/workflows/build-package.yml
name: Build and Package Universal Widget

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target platform (e.g., Zendesk, Salesforce, ServiceNow)'
        required: true
        default: 'Zendesk'

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout universal-widget-v2 repository
        uses: actions/checkout@v4
        with:
          path: universal-widget-v2

      - name: Checkout widget-templates repository
        uses: actions/checkout@v4
        with:
          repository: soumyabera-aisera/widget-templates # Replace with your actual template repo
          path: widget-templates

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies for universal-widget-v2
        run: npm install
        working-directory: universal-widget-v2

      - name: Build Universal Widget for Zendesk
        if: github.event.inputs.platform == 'Zendesk'
        run: npm run build:zendesk
        working-directory: universal-widget-v2 # Run build command from within the widget repo

      - name: Assemble Zendesk App Package
        if: github.event.inputs.platform == 'Zendesk'
        run: |
          echo "Assembling Zendesk package..."
          # Create the Zendesk app package directory at the root of the runner's workspace
          mkdir -p zendesk-app-package
          # Copy the built HTML file from universal-widget-v2/dist-zendesk to zendesk-app-package
          cp universal-widget-v2/dist-zendesk/index.html zendesk-app-package/
          # Copy Zendesk specific scaffolding files from widget-templates
          cp widget-templates/zendesk-template/manifest.json zendesk-app-package/
          mkdir -p zendesk-app-package/translations
          cp widget-templates/zendesk-template/translations/en.json zendesk-app-package/translations/
          # Copy assets (logos, etc.) from widget-templates/zendesk-template/assets to zendesk-app-package/assets
          mkdir -p zendesk-app-package/assets
          cp widget-templates/zendesk-template/assets/* zendesk-app-package/assets/ || true # Allow failure if dir is empty
          echo "Zendesk package content:"
          ls -R zendesk-app-package/
        working-directory: . # Run from the root of the runner to manage files from both checked-out repos

      - name: Create Zendesk App Zip
        if: github.event.inputs.platform == 'Zendesk'
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'zendesk-universal-widget.zip'
          directory: 'zendesk-app-package' # This parameter specifies the directory to zip
          path: '.' # Zip the contents of the specified 'directory'
          exclusions: '*.git* /*node_modules/*'

      - name: Upload Zendesk Artifact
        if: github.event.inputs.platform == 'Zendesk'
        uses: actions/upload-artifact@v4
        with:
          name: zendesk-universal-widget
          path: zendesk-universal-widget.zip
          retention-days: 5

      - name: Handle Salesforce (Not Implemented Yet)
        if: github.event.inputs.platform == 'Salesforce'
        run: echo "Salesforce packaging is not yet implemented. Please refer to the documentation for manual steps."

      - name: Handle ServiceNow (Not Implemented Yet)
        if: github.event.inputs.platform == 'ServiceNow'
        run: echo "ServiceNow packaging is not yet implemented. Please refer to the documentation for manual steps."